name: cncboschai
channels:
  - defaults
dependencies:
  - python=3.10.11
  - pip=23.1.2
  - pip:
      - datasets==2.12.0
      - evaluate==0.4.0
      - pre-commit==3.3.3
      - scikit-learn==1.2.2
      - seqeval==1.2.2
      - torch==2.0.1
      - transformers==4.28.1
      - tqdm==4.65.0
